const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('yuki', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  llmChat: (payload) => ipcRenderer.invoke('llm-chat', payload),
  captureScreen: (opts) => ipcRenderer.invoke('capture-screen', opts || {}),
  ttsSpeak: (text) => ipcRenderer.invoke('tts-speak', text),
  transcribeAudio: (payload) => ipcRenderer.invoke('transcribe-audio', payload || {}),
  getMemory: () => ipcRenderer.invoke('get-memory'),
  updateMemory: (patch) => ipcRenderer.invoke('update-memory', patch),
  addFact: (text) => ipcRenderer.invoke('add-fact', text),
  runAction: (action) => ipcRenderer.invoke('run-action', action),
  getActiveWindow: () => ipcRenderer.invoke('get-active-window'),
  readTextFile: (p) => ipcRenderer.invoke('read-text-file', p),
  listDir: (p) => ipcRenderer.invoke('list-dir', p),
  writeTextFile: (p, content) => ipcRenderer.invoke('write-text-file', p, content),
  runShell: (command, cwd) => ipcRenderer.invoke('run-shell', command, cwd),
  getSpecialPath: (name) => ipcRenderer.invoke('get-special-path', name),
  moveWindow: (dx, dy) => ipcRenderer.send('move-window', dx, dy),
  setRecording: (v) => ipcRenderer.send('recording-state', !!v),
  showMenu: () => ipcRenderer.send('show-menu'),
  focusApp: () => ipcRenderer.invoke('focus-app'),
  onLoadModel: (cb) => ipcRenderer.on('load-model', (_e, p) => cb(p)),
  onNoModel: (cb) => ipcRenderer.on('no-model', () => cb()),
  onInputMode: (cb) => ipcRenderer.on('input-mode', (_e, m) => cb(m)),
  onFlip: (cb) => ipcRenderer.on('set-model-flip', (_e, v) => cb(v)),
  onGlobalPtt: (cb) => ipcRenderer.on('global-ptt', (_e, phase) => cb(phase)),
  onWakeWordToggle: (cb) => ipcRenderer.on('wake-word-toggle', (_e, v) => cb(v)),
});
